version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ePantry"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mns36ajvv3ar"
s3_prefix = "ePantry"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
